

readXML: readXML.cpp data_structure.h  
	$(CXX) -std=c++11 readXML.cpp tinyxml/tinyxml.cpp tinyxml/tinyxmlerror.cpp tinyxml/tinyxmlparser.cpp tinyxml/tinystr.cpp -Ltinyxml/ -oreadXML

clean:
	rm readXML



