files:
  log: "log"
  script_wrapper: "output/make_all_plots.sh"


plots:
  msd: True
  msd_data_prefix: "msd_"
  msd_atoms: 'Al   B   N'


  rdf: True
  rdf_data_prefix: "rdf_"
  rdf_atoms: 'Al B N'
  rdf_bins: 500
  rdf_cut_half_lv: True
  rdf_plot_type: "lines"

  #Global density plots (density of the entire region occupied by rho_atoms
  rho: True
  rho_data_prefix: "rho_"
  rho_atoms: 'Al'


  spatial_distribution: True
  collapse_dimension: 2   #x=0, y=1, z=2
  lattice_atoms: 'B N'
  liquid_atoms: 'Al'
  nbins_x: 50
  nbins_y: 50

  







