files:
  log: "log"
  script_wrapper: "output/make_all_plots.sh"


plots:
  msd: False
  msd_data_prefix: "msd_"
  msd_atoms: 'Al   '


  rdf: False
  rdf_data_prefix: "rdf_"
  rdf_atoms: 'Al '
  rdf_bins: 500
  rdf_cut_half_lv: True
  rdf_plot_type: "lines"

  #Global density plots (density of the entire region occupied by rho_atoms
  rho: False
  rho_data_prefix: "rho_"
  rho_atoms: 'Al'


  spatial_distribution_projection: True
  spatial_distribution_lattice: True
  collapse_dimension: 2
  lattice_atoms: ' '
  liquid_atoms: 'Al'
  nbins_x: 75
  nbins_y: 75

  forces: True
  forces_from_atom: 'Al'
  forces_to_atoms: 'Al'
  forces_bins: 250








